project:
  name: Example PrimerForge Project
  version: 0.1.0

reference_taxon:
  rank: species
  name: Oreochromis niloticus

contrast_taxa:
  - rank: genus
    name: Oreochromis

  - rank: genus
    name: Sarotherodon

  - rank: genus
    name: Coptodon

marker:
  gene: CYTB

database:
  source: NCBI
  db: nucleotide

download:
  include_complete_genomes: true
  include_partial_sequences: true
  max_records: 1000

ncbi:
  email: "your_email@example.com"
  api_key: ""

primer:
  min_length: 20
  max_length: 24
  min_tm: 58
  max_tm: 62
  min_gc: 40
  max_gc: 60
  min_product: 80
  max_product: 150
